title = "Amphitheatre"
description = "Instantly spin up fresh, automated dev environments in the cloud and start developing within seconds."

# The URL the site will be built for
base_url = "https://amphitheatre.app"

# The default language; used in feeds and search index
# Note: the search index doesn't support Chinese/Japanese/Korean Languages
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to generate a feed file for the site
generate_feed = true

# When set to "true", the generated HTML files are minified.
minify_html = false

# Whether to build a search index to be used later on by a JavaScript library
# When set to "true", a search index is built from the pages and section
# content for `default_language`.
build_search_index = false

sort_by = "weight"

[markdown]
# Whether to do syntax highlighting.
# Theme can be customised by setting the `highlight_theme`
# variable to a theme supported by Zola
highlight_code = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

[extra]
# Put all your custom variables here

# Set HTML file language
language_code = "en-US"

# Set theme-color meta tag for Chrome browser
theme_color = "#fff"

# More about site's title
title_separator = "|"  # set as |, -, _, etc
title_addition = ""


# Set date format in blog publish metadata
timeformat = "%B %e, %Y" # e.g. June 14, 2021
timezone = "America/New_York"

# Edit page on reposity or not
edit_page = false
docs_repo = "https://github.com/amphitheatre-app/website"
repo_branch = "master"

## Math settings
# options: true, false. Enable math support globally,
# default: false. You can always enable math on a per page.
math = false
library = "katex"  # options: "katex", "mathjax". default is "katex".

toc = false

[languages.zh]
title = "Amphitheatre"
description = "立即在云端快速创建全新的自动化开发环境，并开始使用按需预配置的工具、库和依赖项进行开发。"
build_search_index = false

[translations]
label_table_contents = "On this page"
label_edit_button = "View on Github"
label_edit_tips = "View and edit this file on Github"
search_placeholder = "Search docs..."
label_sidebar_title = "Browse docs"

menu_documentation = "Documentation"

label_en = "English"
label_zh = "简体中文"

[languages.zh.translations]
label_table_contents = "快速导航"
label_edit_button = "在 Github 上查看"
label_edit_tips = "在 Github 上查看或编辑此文件"
search_placeholder = "搜索此文档..."
label_sidebar_title = "浏览文档"

menu_documentation = "文档"

# [[extra.menu.main]]
# name = "Features"
# url = "/features"
# weight = 10

# [[extra.menu.main]]
# name = "Pricing"
# url = "/pricing"
# weight = 20

# [[extra.menu.main]]
# name = "Customers"
# url = "/customers"
# weight = 30

[[extra.menu.main]]
name = "documentation"
url = "https://docs.amphitheatre.app"
weight = 40
trans = true

# [[extra.menu.main]]
# name = "Community"
# url = "/community"
# weight = 50

# [[extra.menu.main]]
# name = "About"
# url = "/about"
# weight = 60

[[extra.menu.social]]
name = "GitHub"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>'
url = "https://github.com/amphitheatre-app"
post = "v0.1.0"
weight = 20

[extra.footer]
copyright = "Copyright © 2023 The Amphitheatre Authors. All rights reserved. Open source licensed under the Apache License, Version 2.0"

# Products
[[extra.footer.nav]]
name = "Products"

[[extra.footer.nav.list]]
name = "Features"
url ="/features"

[[extra.footer.nav.list]]
name = "Pricing"
url = "/pricing"

[[extra.footer.nav.list]]
name = "Integrations"
url = "/integrations"

[[extra.footer.nav.list]]
name = "Docs"
url = "https://docs.amphitheatre.app"

# Use Cases
[[extra.footer.nav]]
name = "Use Cases"

[[extra.footer.nav.list]]
name = "Everyday Tasks"
url ="/solutions/everyday-tasks"

[[extra.footer.nav.list]]
name = "Reporting"
url = "/solutions/reporting"

[[extra.footer.nav.list]]
name = "Data Enrichment"
url = "/solutions/data-enrichment"

[[extra.footer.nav.list]]
name = "Internal Tools"
url = "/solutions/interal-tools"

# Company
[[extra.footer.nav]]
name = "Company"

[[extra.footer.nav.list]]
name = "About"
url ="/about"

[[extra.footer.nav.list]]
name = "Community"
url = "/community"

[[extra.footer.nav.list]]
name = "Forum"
url = "https://forum.amphithreatre.app"

[[extra.footer.nav.list]]
name = "Blog"
url = "https://blog.amphithreatre.app"

[[extra.footer.nav.list]]
name = "Affiliates"
url = "/affiliates"

# Legal
[[extra.footer.nav]]
name = "Legal"

[[extra.footer.nav.list]]
name = "Security"
url ="/security"

[[extra.footer.nav.list]]
name = "Terms of Use"
url = "/terms"

[[extra.footer.nav.list]]
name = "Privacy Policy"
url = "/privacy"

[[extra.footer.nav.list]]
name = "Terms of integrations"
url = "/terms/integrations"

[[extra.footer.nav.list]]
name = "Imprint"
url = "/imprint"
